Update 3._Data_structure_description_language.md
UAVCAN/uavcan.github.io pull request #16
Opened 2017-07-17 08:39 UTC by hamishwillee

@pavel-kirienko There is little that I can add to this other than some minor playing with the English. It is quite "wordy" but also precise and fairly clear. I did get a little bit worn down towards the end. I'll add some additional comments/question later this evening. 

A few general comments on the changes:
- Use "must" in preference to "shall". Shall is a now-imprecise legal term meaning "a duty to do" (or similar) when generally we mean "is required".
- There are a lot of cases where we say "see below" or "and in a later section of the specification.". I quite like to link those (but have not done so). 
- There are quite a few notes. YOu might want to consider adding "asides" including notes, tips, warnings that highlight some of this stuff.

Some of the changes aren't actually big improvements. For example, I wanted in the section on File hierarchy to start by explaining the mapping. It didn't "quite work as planned" - but I don't believe the shape is any worse than currently, and may just be a little more readable.

2017-07-17 08:40 UTC, hamishwillee commented on Specification/3._Data_structure_description_language.md
> -Every data structure is defined in a separate DSDL definition file.
I remove this line because it is in first sentence of following section.

2017-07-17 10:05 UTC, hamishwillee commented
The "Field naming" section looks like this:
---
First definition:
```
uint8 a
uint8 b
```
Second definition:
```
uint8 b
uint8 a
```

What it says is that the field names must match exactly, but it doesn't quite capture that because what I'm seeing in the example is that they do match, just they have been reordered.

So what I think we're trying to say here is that the binary encoding follows the order of declaration and must match in both name and type. Even if I'm wrong about what is being said here, this is obviously a little unclear or I'd get it.

2017-07-17 10:18 UTC, hamishwillee commented
The signature section is pretty clear overall but ...

* Where it says "It is important to understand that DSDL signature is not the same as data type signature." 
   * This is a good case where a "Note" aside would be useful. The text is useful and should be highlighted, but doesn't quite fit with the flow.
   *  It becomes obvious why this is so, but perhaps we should spell it out. E.g. "but not it should probably say "It is important to understand that DSDL signature is not the same as data type signature (because the data type may reference definitions stored in several files).

* I don't see from this doc how the signatures are actually sent and compared. Is this something that is "magic" at this point in the definition (i.e. is the signature is appended to every message?)
* Similarly, the aggregate signature sounds useful, but not clear who uses this/when/why
* The grouping "Signature" topic could perhaps introduce the concepts a bit earlier.

2017-07-17 10:19 UTC, hamishwillee commented
Where it says "the vendor's legal entity" - is this just handy shorthand or is it a suggestion? It just seems an odd term to use.

2017-07-17 10:25 UTC, hamishwillee commented
For "Data type ID"

1. Should we state the ID ranges reserved for vendors? (vs standard). 
2. Would I be correct in thinking that just the id gets sent in messages (ie not the namespace?) and data type? (because otherwise the data type would be unique within vendor).

2017-07-17 10:35 UTC, hamishwillee commented on Specification/3._Data_structure_description_language.md
> +Each DSDL definition file specifies exactly one data structure that can be used for message broadcasting or a pair of structures that can be used for service invocation data exchange.
I found it annoying that we said "just one structure" and then immediately mentioned service invocation which uses 2.

2017-07-17 10:35 UTC, hamishwillee commented on Specification/3._Data_structure_description_language.md
> +The DSDL compiler will implicitly convert the type of an initializer expression to the constant type if
@pavel-kirienko I think I may have stuffed up here. I was thinking of the compiler as separate from the spec, but actually this defines the behaviour we expect of DSDL compilers as well (that may be separately written from the project). So this should be "must" right?

2017-07-17 10:35 UTC, hamishwillee commented on Specification/3._Data_structure_description_language.md
> +Comments are ignored by the DSDL compiler.
As above - should be "must"?

2017-07-17 10:36 UTC, hamishwillee commented
I think that's all for now, though I will try find time to do further review tomorrow when I'm fresh.

2017-07-18 19:55 UTC, pavel-kirienko requested changes

2017-07-18 19:55 UTC, pavel-kirienko commented on Specification/3._Data_structure_description_language.md
> -Every data structure is defined in a separate DSDL definition file.
You are right here.

2017-07-18 19:55 UTC, pavel-kirienko commented on Specification/3._Data_structure_description_language.md
> +Each DSDL definition file specifies exactly one data structure that can be used for message broadcasting or a pair of structures that can be used for service invocation data exchange.
Excellent. The old wording was a remnant of a very early RFC document that used to be updated and rewritten left and right, so eventually it became a bit incoherent at places. You are probably going to find similar blunders in the following chapters of the specification. Thanks for fixing that.

2017-07-18 19:55 UTC, pavel-kirienko commented on Specification/3._Data_structure_description_language.md
> +Fields can be either a primitive data type (primitive data types are defined below) or a nested data structure.
"Type" is a property of the entity "Field". Saying that fields can be a data type is incorrect. I propose the following wording:

> Fields can be either of a primitive data type

Note the "of". Although I'm not against any equivalent wording here.

2017-07-18 19:55 UTC, pavel-kirienko commented on Specification/3._Data_structure_description_language.md
> +The DSDL compiler will implicitly convert the type of an initializer expression to the constant type if
I think it's a common practice to define a language by describing the expected behavior of its compiler. Look at the C++ standard, for example.

I think we should use "must" here. I thought that "shall" and "must" can be used interchangeably in this context (per RFC2119), can they not?

2017-07-18 19:55 UTC, pavel-kirienko commented on Specification/3._Data_structure_description_language.md
> +Comments are ignored by the DSDL compiler.
Yes.

2017-07-18 20:06 UTC, pavel-kirienko commented
> Use "must" in preference to "shall". Shall is a now-imprecise legal term meaning "a duty to do" (or similar) when generally we mean "is required".

Thanks, I didn't know that.

> There are a lot of cases where we say "see below" or "and in a later section of the specification.". I quite like to link those (but have not done so).

It's a trade-off between ease of reading and the ease of maintenance. Lots of cross-links can be very hard to maintain, so I trust the reader to be able to navigate manually.

> There are quite a few notes. YOu might want to consider adding "asides" including notes, tips, warnings that highlight some of this stuff.

That would require some additional work. The current website engine does not support any advanced formatting options, unfortunately.

> So what I think we're trying to say here is that the binary encoding follows the order of declaration and must match in both name and type. Even if I'm wrong about what is being said here, this is obviously a little unclear or I'd get it.

You are right, so if you think that the current wording is a bit unclear, feel free to amend it.

> This is a good case where a "Note" aside would be useful. The text is useful and should be highlighted, but doesn't quite fit with the flow.

Perhaps. Do you think we should really extend the website with this new sidenoting capability? I would probably opt for more urgent tasks we have at hand now.

> It becomes obvious why this is so, but perhaps we should spell it out. E.g. "but not it should probably say "It is important to understand that DSDL signature is not the same as data type signature (because the data type may reference definitions stored in several files).

Okay.

> I don't see from this doc how the signatures are actually sent and compared. Is this something that is "magic" at this point in the definition (i.e. is the signature is appended to every message?)

> Similarly, the aggregate signature sounds useful, but not clear who uses this/when/why

Signatures are not sent anywhere unless requested. The next chapter (about the transport layer) explains how they are used.

2017-07-18 22:34 UTC, pavel-kirienko commented
> Where it says "the vendor's legal entity" - is this just handy shorthand or is it a suggestion? It just seems an odd term to use.

It's a suggestion that a company, say, Zubax, should use a vendor-specific namespace named `zubax`.

> Should we state the ID ranges reserved for vendors? (vs standard).

Yes, they are reserved. The ranges are documented in the chapter 5. Perhaps we should put another forward-reference?

> Would I be correct in thinking that just the id gets sent in messages (ie not the namespace?) and data type? (because otherwise the data type would be unique within vendor).

Yes, only ID is exchanged over the bus, not the name.

2017-07-18 23:35 UTC, hamishwillee commented on Specification/3._Data_structure_description_language.md
> +Fields can be either a primitive data type (primitive data types are defined below) or a nested data structure.
Very precise :-) Will fix by changing to "The field type can be either a primitive data type ..."

2017-07-18 23:44 UTC, hamishwillee commented on Specification/3._Data_structure_description_language.md
> +The DSDL compiler will implicitly convert the type of an initializer expression to the constant type if
> I think it's a common practice to define a language by describing the expected behavior of its compiler. Look at the C++ standard, for example.

You would know better than me. Even so, you can use a tense to say what the compiler will do (as though already written) or must do (as though this is a spec for the compiler). 
In any case, it makes sense, and what is far more important is not the convention we use, but that we are consistent.

> I think we should use "must" here. I thought that "shall" and "must" can be used interchangeably in this context (per RFC2119), can they not?

You're absolutely right that they can and are often used interchangeably. Nitpickers will argue that "shall" implies that something has a "duty to do" - which has some wriggle room. I don't really hold with that - we know what it means.

The reason I prefer "must" is that it is completely unambiguous and is used in common speech and writing. By contrast shall is rarely used outside of legalese.

Anyway. Will change. Thanks.

2017-07-18 23:45 UTC, hamishwillee commented on Specification/3._Data_structure_description_language.md
> +Comments are ignored by the DSDL compiler.
Will fix

2017-07-19 00:39 UTC, hamishwillee commented
>> There are a lot of cases where we say "see below" or "and in a later section of the specification.". I quite like to link those (but have not done so).

> It's a trade-off between ease of reading and the ease of maintenance. Lots of cross-links can be very hard to maintain, so I trust the reader to be able to navigate manually.

Agree in principle. Care needs to be taken though that the context of "below" is obvious - so often "see in the "blah blah blah section" is better. I don't think there are too many links to include here.

I won't go back and check this whether we've been clear enough here, but will keep in mind for next doc.

>> This is a good case where a "Note" aside would be useful. The text is useful and should be highlighted, but doesn't quite fit with the flow.

> Perhaps. Do you think we should really extend the website with this new sidenoting capability? I would probably opt for more urgent tasks we have at hand now.

You know your priorities. This is definitely a "nice to have", but not essential. 

>>  So what I think we're trying to say here is that the binary encoding follows the order of declaration and must match in both name and type. Even if I'm wrong about what is being said here, this is obviously a little unclear or I'd get it.

> You are right, so if you think that the current wording is a bit unclear, feel free to amend it.

I have amended this (please check). We could take this further and merge with the preceding section since they cover 2 closely-related cases of binary compatibility. 

> Signatures are not sent anywhere unless requested. The next chapter (about the transport layer) explains how they are used.

I added a forward reference and slightly tidied this introduction.

>> Where it says "the vendor's legal entity" - is this just handy shorthand or is it a suggestion? It just seems an odd term to use.

> It's a suggestion that a company, say, Zubax, should use a vendor-specific namespace named zubax.

OK, I have made this a "must use their own namespace" but made it more of a suggestion/company name rather than legal name:

"Vendors must define their specific data types in a separate namespace, which should typically be named to match their company name."

>> Should we state the ID ranges reserved for vendors? (vs standard).

> Yes, they are reserved. The ranges are documented in the chapter 5. Perhaps we should put another forward-reference?

Yes. Done.  I put all the notes here in a "note" section.

2017-07-19 00:40 UTC, hamishwillee commented
@pavel-kirienko I think this addresses all our discussions (ie ready for your re-review).

2017-07-19 12:39 UTC, pavel-kirienko commented
> I have amended this (please check). We could take this further and merge with the preceding section since they cover 2 closely-related cases of binary compatibility.

I think we should keep them separate, because although similar, they review different issues.

This looks good to me, I'm merging this. Thanks a lot.

2017-07-19 12:39 UTC, pavel-kirienko approved these changes

2017-07-19 12:39 UTC, merged

2017-07-20 01:56 UTC, hamishwillee commented
Great!